<div class="field field-name-facebook_profile_link">
    <label class="label" for="facebook_profile_link"><span>Facebok Profile Link</span></label>
    <div class="control">
        <input type="text" id="facebook_profile_link" name="facebook_profile_link" value="" title="" class="input-text" autocomplete="off">
    </div>
</div>
<div class="field field-name-youtube_page_link">
    <label class="label" for="youtube_page_link"><span>YouTube Page Link</span></label>
    <div class="control">
        <input type="text" id="youtube_page_link" name="youtube_page_link" value="" title="YouTube Page Link" class="input-text" autocomplete="off">
    </div>
</div>
<div class="field field-name-about_yourself">
    <label class="label" for="about_yourself"><span>About You</span></label>
    <div class="control">
        <textarea id="about_yourself" name="about_yourself" title="About You" class="input-text" autocomplete="off"></textarea>
    </div>
    <input type="hidden" name="request_for_vv_user" value="1" />
</div>