<?php
/**
 *
 * SM Listing Tabs - Version 2.5.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
if ($this->_isAjax()) {
    $products = $this->_ajaxLoad();
    $config = $this->_getConfig();
} else {
    $config = $this->getData('config');
    $products = $this->getData('products');
}
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$viewMode = 'grid';
$image = 'category_page_grid';
$showDescription = false;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

$type_loadmore = $config['type_show'] == 'loadmore' ? true : false;
$cls_mark = $type_loadmore ? ' ltabs-mark ' : '';

$_config = $this->helper('Sm\Emarket\Helper\Data');

$show_addtocart = $_config->getAdvanced('show_addtocart_button');
$show_addtocompare = $_config->getAdvanced('show_compare_button');
$show_addtowishlist = $_config->getAdvanced('show_wishlist_button');
$show_newlabel = $_config->getAdvanced('show_newlabel');
$new_label_text = $_config->getAdvanced('new_label_text');
$show_salelabel = $_config->getAdvanced('show_salelabel');
$sale_label_text = $_config->getAdvanced('sale_label_text');
$show_pecent = $_config->getAdvanced('show_salediscount');
$homeStyle = $_config->getThemeLayout('home_style');

/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
?>
<div class="products wrapper <?php /* @escapeNotVerified */
echo $viewMode; ?> products-<?php /* @escapeNotVerified */
echo $viewMode; ?>">
    <?php $iterator = 1; ?>
    <ol class="products list items product-items  <?php echo $type_loadmore == false ? ' owl-carousel ' : ''; ?>" <?php echo $type_loadmore ? 'data-liffect="fadeIn"' : ''; ?>>
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach ($products as $_product):

            ?>
            <?php /* @escapeNotVerified */
            echo ($iterator++ == 1) ? '<li class="item product product-item ' . $cls_mark . '">' : '</li><li class="item product product-item ' . $cls_mark . '">' ?>
            <div class="product-item-info  item-inner style1" data-container="product-grid">
                <?php
                $productImage = $block->getImage($_product, $image);
                if ($pos != null) {
                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                        . 'top:' . $productImage->getHeight() . 'px;"';
                }
                ?>
                <?php
                if ((int)$config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
                    $specialToDate = $_product->getSpecialToDate();
                    ?>
                    <div class="deals-countdown"
                         data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
                        <div class="deals-time time-day">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-hours">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-mins">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-secs">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                    </div>
                <?php } ?>
                <?php // Product Image 
                ?>
                <div class="box-image">
                    <a href="<?php /* @escapeNotVerified */
                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>

                    <div class="product actions product-item-actions bottom-action">
                        <?php if ($show_addtocart) { ?>
                            <?php if ($_product->isSaleable()): ?>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                echo $postParams['action']; ?>" method="post">
                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */
                                    echo $postParams['data']['product']; ?>">
                                    <input type="hidden" name="<?php /* @escapeNotVerified */
                                    echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
                                    echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                    <input type="hidden" name="form_key" value="<?php echo $block->_getFormKey(); ?>"/>
                                    <button type="submit"
                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                            class="action tocart btn-action primary btn-cart">
                                        <span><?php /* @escapeNotVerified */
                                            echo __('Add to Cart') ?></span>
                                    </button>
                                </form>
                            <?php else: ?>
                                <?php if ($_product->getIsSalable()): ?>
                                    <div class="stock available"><span><?php /* @escapeNotVerified */
                                            echo __('In stock') ?></span></div>
                                <?php else: ?>
                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                            echo __('Out of stock') ?></span></div>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php } ?>

                        <?php if ($show_addtowishlist) { ?>
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                <a href="#"
                                   data-post='<?php /* @escapeNotVerified */
                                   echo $block->getAddToWishlistParams($_product); ?>'
                                   class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist"
                                   title="<?php /* @escapeNotVerified */
                                   echo __('Add to Wish List') ?>">
                                    <span><?php /* @escapeNotVerified */
                                        echo __('Add to Wish List') ?></span>
                                </a>
                            <?php endif; ?>
                        <?php } ?>

                        <?php if ($show_addtocompare) { ?>
                            <?php if ($block->getAddToCompareUrl()): ?>
                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                <a href="#" class="action tocompare btn-action link-compare"
                                   data-post='<?php /* @escapeNotVerified */
                                   echo $compareHelper->getPostDataParams($_product); ?>'
                                   title="<?php /* @escapeNotVerified */
                                   echo __('Add to Compare') ?>">
                                    <span><?php /* @escapeNotVerified */
                                        echo __('Add to Compare') ?></span>
                                </a>
                            <?php endif; ?>
                        <?php } ?>
                    </div>
                </div>

                <div class="product details product-item-details box-info">
                    <?php
                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                    ?>
                    <h2 class="product name product-item-name product-name">
                        <a class="product-item-link"
                           href="<?php /* @escapeNotVerified */
                           echo $_product->getProductUrl() ?>">
                            <?php /* @escapeNotVerified */
                            echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                        </a>
                    </h2>
                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
                    <?php /* @escapeNotVerified */
                    echo $block->getProductPrice($_product) ?>
                    <?php echo $block->getProductDetailsHtml($_product); ?>

                    <div class="product-item-inner">

                    </div>
                    <div class="seller-info">
			<?php
			$helper = $this->helper('Ehub\Catalog\Helper\Data');
			echo $helper->getSellerHtml($_product);
			?>
			</div>
                </div>
                
            </div>
            <?php echo ($iterator == count($products) + 1) ? '</li>' : '' ?>
        <?php endforeach; ?>
    </ol>
</div>
